part of 'view.dart';

class TwoFaAuthenticatorApp extends StatelessWidget {
  const TwoFaAuthenticatorApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const CustomAppBar(
        title: '2FA Activation',
      ),
      backgroundColor: context.white,
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16.0),
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const CustomProgressBar(),
              const SizedBox(height: 24),
              Text(
                'Step 1 of 5',
                style: context.sixteen500.withColor(context.primary500),
              ),
              const SizedBox(height: 8),
              const CustomTitleSubtitle(
                title: 'Authenticator App',
                subtitle:
                    'Use a mobile app like Google Authenticator to generate verification codes.',
              ),
              const SizedBox(height: 32),
              CustomTitleSubtitle(
                titleStyle: context.sixteen600,
                subtitleStyle: context.sixteen400,
                title: '1. Download App',
                subtitle:
                    'Install your Authenticator app on your device. Available for iOS and Android.',
              ),
              const SizedBox(height: 32),
              CustomTitleSubtitle(
                titleStyle: context.sixteen600,
                subtitleStyle: context.sixteen400,
                title: '2. Scan QR Code',
                subtitle: 'Scan this QR code using the app.',
              ),
              const SizedBox(height: 16),
              const QrCodeImage(),
              const SizedBox(height: 24),
              Center(
                child: Text(
                  "Can't scan the QR? Enter the key manually.",
                  style: context.sixteen400,
                ),
              ),
              const SizedBox(height: 24),
              const KeyWidget(),
              const SizedBox(height: 30),
              CustomTitleSubtitle(
                titleStyle: context.sixteen600,
                subtitleStyle: context.sixteen400,
                title: '3. Finish Setup',
                subtitle: 'Enter the verification code generated by your app.',
              ),
              const SizedBox(height: 16),
              const CodeTextField(),
              const SizedBox(height: 16),
              const VerifyButton(),
              const SizedBox(height: 20),
            ],
          ),
        ),
      ),
    );
  }
}
