name: rdm_builder_customer
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  common:
    path: packages/common


  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  formz: ^0.4.1
  go_router: ^13.2.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  intl: ^0.18.1
  pinput: ^5.0.0
  smooth_page_indicator: ^1.2.0
  progress_stepper: ^3.1.0
  intl_phone_field: ^3.2.0
  intl_phone_number_input: ^0.7.4
  dio: ^5.5.0+1
  percent_indicator: ^4.2.3
  dotted_border: ^2.1.0
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating_bar: ^4.0.1
  flutter_chat_bubble: ^2.0.2
  lottie: ^3.1.2
  image_picker: ^1.0.7
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  #onfido_sdk: ^6.2.0
  country_picker: ^2.0.26
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
    - assets/images/
    - assets/animation/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
