import 'package:common/common.dart';
import 'package:common/widgets/custom_alert_dialog.dart';
import 'package:flutter/material.dart';
import 'package:rdm_builder_customer/widgets/custom_title_subtitle.dart';

class TwoFaAuthenticatorApp extends StatelessWidget {
  const TwoFaAuthenticatorApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: const CustomAppBar(
        title: '2FA Activation',
      ),
      backgroundColor: context.white,
      body: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 16.0),
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const CustomProgressBar(),
              const SizedBox(height: 24),
              Text(
                'Step 1 of 5',
                style: context.sixteen500.withColor(context.primary500),
              ),
              const SizedBox(height: 8),
              const CustomTitleSubtitle(
                title: 'Authenticator App',
                subtitle:
                    'Use a mobile app like Google Authenticator to generate verification codes.',
              ),
              const SizedBox(height: 32),
              CustomTitleSubtitle(
                titleStyle: context.sixteen600,
                subtitleStyle: context.sixteen400,
                title: '1. Download App',
                subtitle:
                    'Install your Authenticator app on your device. Available for iOS and Android.',
              ),
              const SizedBox(height: 32),
              CustomTitleSubtitle(
                titleStyle: context.sixteen600,
                subtitleStyle: context.sixteen400,
                title: '2. Scan QR Code',
                subtitle: 'Scan this QR code using the app.',
              ),
              const SizedBox(height: 16),
              Center(
                child: Image.asset(
                  'assets/qr_image.png',
                  height: 150,
                  width: 150,
                ),
              ),
              const SizedBox(height: 24),
              Center(
                child: Text(
                  "Can't scan the QR? Enter the key manually.",
                  style: context.sixteen400,
                ),
              ),
              const SizedBox(height: 24),
              Container(
                padding: const EdgeInsets.all(8),
                width: double.infinity,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(4),
                  color: context.grey50,
                ),
                child: Center(
                  child: Text(
                    '5R32 3QK6 BZXA TRAC',
                    style: context.sixteen400,
                  ),
                ),
              ),
              const SizedBox(height: 30),
              CustomTitleSubtitle(
                titleStyle: context.sixteen600,
                subtitleStyle: context.sixteen400,
                title: '3. Finish Setup',
                subtitle: 'Enter the verification code generated by your app.',
              ),
              const SizedBox(height: 16),
              const CustomTextFormField(
                hintText: '000-000',
              ),
              const SizedBox(height: 16),
              CustomElevatedButton(
                width: double.infinity,
                text: 'Verify',
                onPressed: () {
                  showDialog<CustomAlertDialog>(
                    context: context,
                    builder: (context) => const CustomAlertDialog(
                      title: '2F Authentication Activated!',
                      subTitle:
                          'Your setup is complete. Use your Google Authenticator app to generate OTP.',
                    ),
                  );
                  Future.delayed(
                    const Duration(seconds: 3),
                    () {
                      Navigator.pop(context);
                    },
                  );
                },
              ),
              const SizedBox(height: 20),
            ],
          ),
        ),
      ),
    );
  }
}

class CustomProgressBar extends StatelessWidget {
  const CustomProgressBar({
    super.key,
    this.selectedIndex = 1,
  });

  final int selectedIndex;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: List.generate(
        5,
        (index) => Expanded(
          child: Container(
            margin: const EdgeInsets.symmetric(horizontal: 4),
            height: 8,
            decoration: ShapeDecoration(
              color:
                  index >= selectedIndex ? context.grey100 : context.primary500,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
